[package]
name = "OmniSwap"
version = "0.1.0"

[addresses]
std = "0x1"
aptos-stdlib = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
omniswap = "_"
token_bridge = "_"
wormhole = "_"
deployer = "_"

[dev-addresses]
omniswap = "0x66"
token_bridge = "0x4450040bc7ea55def9182559ceffc0652d88541538b30a43477364f475f4a4ed"
wormhole = "0x251011524cd0f76881f16e7c2d822f0c1c9510bfd2430ba24e1b3d52796df204"
wrapped_coin = "0xf4f53cc591e5190eddbc43940746e2b5deea6e0e1562b2bba765d488504842c7"
deployer = "0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"

[dependencies.TokenBridge]
git = "https://github.com/OmniBTC/wormhole.git"
rev ="9c2847d6e667851e9343227b5be4f0fa5c73ff6f"
subdir = "aptos/token_bridge"

[dependencies.Wormhole]
git = "https://github.com/OmniBTC/wormhole.git"
rev ="9c2847d6e667851e9343227b5be4f0fa5c73ff6f"
subdir = "aptos/wormhole"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Liquidswap]
git = "https://github.com/pontem-network/liquidswap.git"
rev = 'b89aed9adb96c0b083134765f75be814418be670'
