# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
networks:
  default: rinkeby
  rinkeby:
    chainid: 4
    stargate_router: "0x82A0F5F531F9ce0df1DF5619f74a0d3fA31FF561"
    stargate_chainid: 10001
    stargate_poolid: 1
    usdc: "0x1717A0D5C8705EE89A8aD6E808268D6A826C97A4"
    weth: "0xc778417E063141139Fce010982780140Aa0cD5Ab"
    swap: [ [ "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D", IUniswapV2Router02 ] ]
  bsc-test:
    chainid: 97
    stargate_router: "0xbB0f1be1E9CE9cB27EA5b0c3a85B7cc3381d8176"
    stargate_chainid: 10002
    stargate_poolid: 2
    usdc: "0xF49E250aEB5abDf660d643583AdFd0be41464EfD"
    weth: "0xae13d989dac2f0debff460ac112a837c89baa7cd"
    swap: [ [ "0x9Ac64Cc6e4415144C455BD8E4837Fea55603e5c3", IUniswapV2Router02 ] ]
  avax-test:
    chainid: 43113
    stargate_router: "0x13093E05Eb890dfA6DacecBdE51d24DabAb2Faa1"
    stargate_chainid: 10006
    stargate_poolid: 1
    usdc: "0x4A0D1092E9df255cf95D72834Ea9255132782318"
    weth: "0x9B5828d46A43176F07656e162cCbDc787624468c"
    swap: [ [ "0x6D481b9F59b22B6eB097b986fC06E438d585c039", IUniswapV2Router02AVAX ] ]
  polygon-test:
    chainid: 80001
    stargate_router: "0x817436a076060D158204d955E5403b6Ed0A5fac0"
    stargate_chainid: 10009
    stargate_poolid: 1
    usdc: "0x742DfA5Aa70a8212857966D491D67B09Ce7D6ec7"
    weth: "0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889"
    swap: [ [ "0x8954AfA98594b838bda56FE4C12a09D7739D179b", IUniswapV2Router02 ] ]
  optimism-test:
    stargate_router: "0xCC68641528B948642bDE1729805d6cf1DECB0B00"
    stargate_chainid: 10011
    usdc: "0x567f39d9e6d02078F357658f498F80eF087059aa"
  ftm-test:
    chainid: 4002
    stargate_router: "0xa73b0a56B29aD790595763e71505FCa2c1abb77f"
    stargate_chainid: 10012
    stargate_poolid: 1
    weth: "0x9B5828d46A43176F07656e162cCbDc787624468c"
    usdc: "0x076488D244A73DA4Fa843f5A8Cd91F655CA81a1e"
    swap: [ [ "0x6D481b9F59b22B6eB097b986fC06E438d585c039", IUniswapV2Router02 ] ]
  mainnet:
    stargate_router: "0x8731d54E9D02c286767d56ac03e8037C07e01e98"
    stargate_chainid: 1
    swap: [ [ "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D", IUniswapV2Router02, "https://tokens.uniswap.org/" ] ]
  bsc-main:
    stargate_router: "0x4a364f8c717cAAD9A442737Eb7b8A55cc6cf18D8"
    stargate_chainid: 2
    swap: [ [ "0x10ED43C718714eb63d5aA57B78B54704E256024E", IUniswapV2Router02, "https://tokens.pancakeswap.finance/pancakeswap-top-100.json" ] ]
  avax-main:
    stargate_router: "0x45A01E4e04F14f7A4a6702c74187c5F6222033cd"
    stargate_chainid: 6
    swap: [ [ "0xE54Ca86531e17Ef3616d22Ca28b0D458b6C89106", IUniswapV2Router02AVAX, "https://raw.githubusercontent.com/pangolindex/tokenlists/main/pangolin.swap_tokenlist.json" ] ]
  polygon-main:
    stargate_router: "0x45A01E4e04F14f7A4a6702c74187c5F6222033cd"
    stargate_chainid: 9
    swap: [ [ "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff", IUniswapV2Router02, "https://unpkg.com/quickswap-default-token-list@1.2.38/build/quickswap-default.swap_tokenlist.json" ] ]
  arbitrum-main:
    stargate_router: "0x53Bf833A5d6c4ddA888F69c22C88C9f356a41614"
    stargate_chainid: 10
    swap: [ [ "0xaBBc5F99639c9B6bCb58544ddf04EFA6802F4064", IUniswapV2Router02, "https://bridge.arbitrum.io/token-list-42161.json" ] ]
  optimism-main:
    stargate_router: "0xB0D502E938ed5f4df2E681fE6E419ff29631d62b"
    stargate_chainid: 11
    swap: [ [ "0xE592427A0AEce92De3Edee1F18E0157C05861564", IUniswapV2Router02, "https://static.optimism.io/optimism.swap_tokenlist.json" ] ]
  ftm-main:
    stargate_router: "0xAf5191B0De278C7286d6C7CC6ab6BB8A73bA2Cd6"
    stargate_chainid: 12
    swap: [ [ "0xF491e7B69E4244ad4002BC14e878a34207E38c29", IUniswapV2Router02, "https://docs.spooky.fi/Resources/ftm-token-addresses" ] ]
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}




